import {
  Code,
  Briefcase,
  Palette,
  GraduationCap,
  Star,
  Heart,
  BookOpen,
  DollarSign,
  TrendingUp,
  Scale,
  Settings,
  Sparkles,
} from "lucide-react";

export interface ProfessionCategory {
  id: string;
  name: string;
  description: string;
  icon: any;
  color: string;
  gradientFrom: string;
  gradientTo: string;
  templateIds: string[];
  isAll?: boolean; // Special flag for the "All" category
}

export const professionCategories: ProfessionCategory[] = [
  {
    id: "all",
    name: "All Templates",
    description: "Browse all our professionally designed resume templates across all categories",
    icon: Sparkles,
    color: "#6366f1",
    gradientFrom: "#6366f1",
    gradientTo: "#8b5cf6",
    isAll: true,
    templateIds: [
      // Universal Professional Templates
      "professional",
      "minimal",
      "premium-universal",
      "premium-pro",
      "elite",
      "refined",
      "premium-elite",
      "modern-sidebar",
      "minimalist-geometric",
      "bold-headline",
      "dual-tone",
      "contemporary-split",
      // Fresh Graduates Templates
      "graduate",
      "starter",
      "fresher",
      "premium-fresher",
      "fresher-elite",
      "fresher-minimal-grid",
      "fresher-dark-professional",
      "fresher-color-accent",
      "fresher-timeline",
      "fresher-skills-first",
      "fresher-card-based",
      "fresher-two-tone",
      "fresher-centered-elegant",
      "fresher-geometric",
      "fresher-achievement",
      "fresher-modern-two-column",
      "fresher-professional-sidebar",
      "fresher-clean-modern",
      "fresher-tech-split",
      "fresher-executive-style",
      "fresher-bold-header",
      "fresher-minimalist-two-column",
      "fresher-creative-edge",
      "fresher-professional-grid",
      "fresher-modern-classic",
      "fresher-split-layout",
      "fresher-compact-pro",
      "fresher-elegant-sidebar",
      "fresher-tech-modern",
      "fresher-professional-minimal",
      // Software & Technology Templates
      "frontend",
      "backend",
      "fullstack",
      "senior",
      "senior-frontend",
      "senior-backend",
      "software",
      "tech-grid",
      // New Software Development Templates
      "java-developer",
      "dotnet-developer",
      "devops-engineer",
      "cloud-architect",
      "mobile-developer",
      "react-native-developer",
      "data-engineer",
      "machine-learning-engineer",
      "qa-automation-engineer",
      "security-engineer",
      "python-developer",
      "nodejs-developer",
      "react-developer",
      "go-developer",
      "kubernetes-engineer",
      // Senior/Lead Software Engineering Templates
      "senior-java-developer",
      "senior-dotnet-developer",
      "senior-devops-engineer",
      "lead-backend-engineer",
      "lead-frontend-engineer",
      "senior-fullstack-developer",
      "principal-software-engineer",
      "staff-engineer",
      "engineering-manager",
      "solutions-architect",
      "senior-mobile-engineer",
      "platform-engineer",
      "site-reliability-engineer",
      "backend-api-specialist",
      "frontend-architect",
      // Creative & Design Templates
      "creative-accent",
      "modern",
      "elegant-serif",
      // Business & Leadership Templates
      "executive",
      "sapphire-executive",
      "luxury-timeline",
      "corporate-executive",
      "analyst",
      // Healthcare & Medical
      "medical-professional",
      "healthcare-two-column",
      "nurse-specialist",
      "medical-executive",
      "clinical-minimal",
      // Education & Teaching
      "teacher-professional",
      "academic-scholar",
      "educator-modern",
      "teaching-certified",
      "student-educator",
      // Finance & Accounting
      "cpa-professional",
      "finance-analyst",
      "accounting-executive",
      "auditor",
      "finance-two-column",
      // Sales & Marketing
      "sales-executive",
      "marketing-professional",
      "sales-marketing-hybrid",
      "digital-marketer",
      "sales-manager",
      // Legal & Consulting
      "attorney-professional",
      "legal-counsel",
      "consultant",
      "legal-executive",
      "paralegal",
      // Operations & Project Management
      "project-manager-pmp",
      "operations-manager",
      "pm-executive",
      "agile-scrum",
      "operations-two-column",
      // New Universal Professional Templates
      "executive-modern",
      "corporate-blue",
      "professional-sidebar",
      "minimalist-pro",
      "classic-elegant",
      "business-modern",
      "professional-timeline",
      "clean-corporate",
      "modern-professional",
      "elegant-professional",
      "professional-grid",
      "business-elite",
      "corporate-clean",
      "professional-classic",
      "modern-business",
      // New Professional Templates (22 new templates)
      "timeline-elegance",
      "executive-minimal",
      "sidebar-accent",
      "geometric-modern",
      "two-tone-classic",
      "bordered-elegance",
      "column-divide",
      "compact-professional",
      "code-minimal",
      "tech-stack-pro",
      "github-style",
      "developer-grid",
      "terminal-theme",
      "algo-engineer",
      "fullstack-modern",
      "devops-pro",
      "ml-engineer",
      "artistic-bold",
      "designer-showcase",
      "creative-timeline",
      "colorful-modern",
      "asymmetric-creative",
      // New 2024 Universal Templates
      "strategic-executive",
      "professional-sphere",
      "global-professional",
      "professional-horizon",
      "executive-prime",
      "corporate-momentum",
      "professional-ascend",
      "global-elite",
      "executive-vision",
      "corporate-fusion",
      "professional-zenith",
      "executive-core",
      // New 2024 Tech Templates
      "code-craftsman",
      "tech-pioneer",
      "dev-architecture",
      "software-master",
      "tech-vanguard",
      "code-sphere",
      "dev-elite",
      "tech-horizon",
      "software-craftsman",
      "code-vision",
      "dev-prime",
      "tech-crafted",
      "software-vision",
      "code-pinnacle",
      "dev-momentum",
      // 2025 New Software/Tech Templates
      "dark-mode-dev",
      "code-snippet",
      "api-doc",
      "stackoverflow-inspired",
      "github-profile",
      "terminal-console",
      "json-resume",
      "monospace-tech",
      "blueprint-design",
      "system-architect",
      "cloud-native",
      "microservices-dev",
      "agile-scrum",
      "tech-lead",
      "open-source",
      "fullstack-pro",
      "data-science",
      "cyber-security",
      "blockchain-dev",
      "ai-engineer",
      "mobile-dev",
      // New 2024 Creative Templates
      "creative-canvas",
      "design-maestro",
      "artistic-vision",
      "creative-pulse",
      "design-pinnacle",
      "artistic-horizon",
      "creative-crafted",
      "design-sphere",
      "artistic-momentum",
      "creative-horizon",
      // 2025 New Creative Templates
      "magazine-creative",
      "portfolio-showcase",
      "artistic-grid",
      "bold-typography",
      "color-splash",
      "minimal-chic",
      "photography-layout",
      "brand-identity",
      "vintage-poster",
      "modern-artist",
      "gallery-layout",
      "editorial-style",
      "urban-designer",
      "pastel-creative",
      "neon-artist",
      "geometric-creative",
      "typewriter-style",
      "ink-brush",
      "collage-art",
      "digital-canvas",
      // New 2024 Fresher Templates
      "graduate-momentum",
      "entry-elite",
      "freshers-vision",
      "graduate-prime",
      "entry-horizon",
      "freshers-crafted",
      "graduate-zenith",
      "entry-sphere",
      // 2025 New Fresher Templates
      "fresher-neon-accent",
      "fresher-glassmorphism",
      "fresher-progressive",
      "fresher-polaroid-style",
      "fresher-ribbon-style",
      "fresher-double-column",
      "fresher-gradient-border",
      "fresher-circular-progress",
      "fresher-modern-tabs",
      "fresher-lightweight",
      "fresher-timeline-dots",
      "fresher-box-shadow",
      "fresher-step-by-step",
      "fresher-left-stripe",
      "fresher-top-bottom",
      "fresher-dash-border",
      "fresher-iconography",
      "fresher-modern-split",
      "fresher-wave-header",
      "fresher-academic-style",
      // 2025 New Universal Profile Templates
      "sidebar-professional-universal",
      "metro-modern-universal",
      "swiss-style-universal",
      "executive-letterhead-universal",
      "diagonal-accent-universal",
      "border-frame-universal",
      "centered-minimal-universal",
      "left-aligned-pro-universal",
      "dual-column-modern-universal",
      "timeline-vertical-universal",
      "badge-style-universal",
      "underline-accent-universal",
      "circle-icon-universal",
      "linear-progress-universal",
      "card-layout-universal",
      "ribbon-header-universal",
      "boxed-sections-universal",
      "left-border-universal",
      "floating-header-universal",
      "monochrome-elegant-universal",
      // 2025 Second Batch Universal Profile Templates
      "gradient-header-universal",
      "split-pane-universal",
      "icon-bar-universal",
      "modern-minimalist-universal",
      "bold-typography-universal",
      "geometric-shapes-universal",
      "color-block-universal",
      "thin-border-universal",
      "asymmetric-layout-universal",
      "classic-serif-universal",
      "professional-compact-universal",
      "wide-margin-universal",
      "top-bar-universal",
      "corner-accent-universal",
      "striped-background-universal",
      "circular-elements-universal",
      "minimal-lines-universal",
      "bold-section-headers-universal",
      "two-tone-split-universal",
      "clean-modern-universal",
      // 2025 Third Batch Universal Profile Templates
      "watermark-style-universal",
      "magazine-layout-universal",
      "hexagonal-pattern-universal",
      "compact-elite-universal",
      "diamond-accent-universal",
      "zigzag-border-universal",
      "stacked-sections-universal",
      "dotted-grid-universal",
      "wave-pattern-universal",
      "chevron-accent-universal",
      "spotlight-header-universal",
      "layered-cards-universal",
      "angular-modern-universal",
      "rounded-corners-universal",
      "retro-professional-universal",
      "newspaper-style-universal",
      "triangular-elements-universal",
      "parallax-style-universal",
      "vertical-timeline-universal",
      "infinity-loop-universal",
      // 2025 New Profession-Specific Templates
      "medical-certification",
      "clinical-excellence",
      "healthcare-professional",
      "nursing-specialist",
      "medical-research",
      "teaching-excellence",
      "modern-educator-profession",
      "academic-educator",
      "curriculum-developer",
      "student-engagement",
      "financial-analyst",
      "accounting-pro",
      "investment-banker",
      "tax-specialist",
      "audit-expert",
      "sales-achievement",
      "marketing-strategist",
      "digital-marketing-pro",
      "brand-manager",
      "executive-sales-leader",
      "corporate-legal-counsel",
      "corporate-law",
      "litigation-attorney",
      "compliance-officer",
      "legal-advisor",
      "project-manager-pro",
      "operations-excellence",
      "process-improvement",
      "supply-chain-manager",
      "agile-project-lead",
      "executive-leadership",
      "ceo-profile",
      "strategic-leader",
      "director-level",
      "vp-executive",
      // 2025 New Universal Professional Templates (Batch 5)
      "executive-corner-accent",
      "minimal-elegance-universal",
      "professional-divider",
      "modern-corporate-grid",
      "business-sidebar-pro",
      "clean-two-column-universal",
      "professional-header-banner",
      "executive-timeline-modern",
      "corporate-border-frame",
      "minimalist-modern-pro",
      "professional-accent-bar",
      "business-clean-layout",
      "executive-split-design",
      "modern-professional-box",
      "corporate-minimalist-pro",
      "professional-vertical-line",
      "business-modern-grid",
      "executive-clean-split",
      "minimal-corporate-pro",
      "professional-modern-edge",
      // 2025 New Software/Tech Templates (Batch 3)
      "react-frontend-pro",
      "node-backend-specialist",
      "fullstack-engineer",
      "python-developer-pro",
      "java-enterprise-template",
      "devops-automation",
      "cloud-solutions-architect",
      "microservices-expert",
      "kubernetes-specialist",
      "docker-container-pro",
      "graphql-developer",
      "typescript-expert",
      "vuejs-developer",
      "angular-specialist",
      "springboot-developer",
      "django-framework-pro",
      "aws-cloud-engineer",
      "azure-devops-specialist",
      "gcp-architect",
      "serverless-developer",
      // 2025 New Software/Tech Templates (Batch 4)
      "rust-developer-pro",
      "scala-engineer",
      "elixir-developer",
      "swift-ios-developer",
      "kotlin-android-dev",
      "flutter-mobile-dev",
      "react-native-expert",
      "tensorflow-ml-engineer",
      "pytorch-developer",
      "mongodb-specialist",
      "postgresql-expert",
      "redis-cache-specialist",
      "elasticsearch-dev",
      "kafka-streaming-expert",
      "cicd-pipeline-engineer",
      // 2025 New Creative/Design Templates (Batch 2)
      "portfolio-minimalist",
      "creative-showcase-grid",
      "art-director-modern",
      "uiux-designer-pro",
      "graphic-design-pro",
      "brand-designer-template",
      "motion-graphics-artist",
      "illustration-portfolio",
      "photography-pro-template",
      "video-editor-creative",
      "threed-modeling-artist",
      "web-designer-modern",
      "product-designer-ux",
      "interaction-designer",
      "visual-storyteller-template",
      // 2025 Simple Universal Professional Templates (Batch 6)
      "clean-professional-simple",
      "simple-executive-layout",
      "minimal-pro-layout",
      "professional-clean-simple",
      "corporate-simple-template",
      "modern-simple-pro",
      "executive-simple-clean",
      "business-simple-modern",
      "professional-easy-read",
      "clean-corporate-simple",
      "simple-modern-executive",
      "minimalist-pro-simple",
      "professional-straightforward",
      "executive-direct-layout",
      "business-clear-template",
      "simple-professional-clean",
      "corporate-easy-layout",
      "modern-clear-pro",
      "professional-plain-simple",
      "executive-plain-layout",
      "simple-business-clean",
      "minimal-direct-template",
      "professional-basic-modern",
      "clean-basic-executive",
      "simple-clear-business",
      "modern-plain-pro",
      "executive-easy-template",
      "professional-readable-layout",
      "clean-readable-pro",
      "simple-structured-template",
    ],
  },
  {
    id: "universal-professional",
    name: "Universal Professional",
    description: "Versatile templates suitable for all industries and roles",
    icon: Star,
    color: "#f59e0b",
    gradientFrom: "#f59e0b",
    gradientTo: "#d97706",
    templateIds: [
      "professional",
      "minimal",
      "premium-universal",
      "premium-pro",
      "elite",
      "refined",
      "premium-elite",
      "modern-sidebar",
      "minimalist-geometric",
      "bold-headline",
      "dual-tone",
      "contemporary-split",
      // New Universal Professional Templates
      "executive-modern",
      "corporate-blue",
      "professional-sidebar",
      "minimalist-pro",
      "classic-elegant",
      "business-modern",
      "professional-timeline",
      "clean-corporate",
      "modern-professional",
      "elegant-professional",
      "professional-grid",
      "business-elite",
      "corporate-clean",
      "professional-classic",
      "modern-business",
      // New Universal Templates
      "timeline-elegance",
      "executive-minimal",
      "sidebar-accent",
      "geometric-modern",
      "two-tone-classic",
      "bordered-elegance",
      "column-divide",
      "compact-professional",
      // New 2024 Universal Templates
      "strategic-executive",
      "professional-sphere",
      "global-professional",
      "professional-horizon",
      "executive-prime",
      "corporate-momentum",
      "professional-ascend",
      "global-elite",
      "executive-vision",
      "corporate-fusion",
      "professional-zenith",
      "executive-core",
      // 2025 New Universal Profile Templates
      "sidebar-professional-universal",
      "metro-modern-universal",
      "swiss-style-universal",
      "executive-letterhead-universal",
      "diagonal-accent-universal",
      "border-frame-universal",
      "centered-minimal-universal",
      "left-aligned-pro-universal",
      "dual-column-modern-universal",
      "timeline-vertical-universal",
      "badge-style-universal",
      "underline-accent-universal",
      "circle-icon-universal",
      "linear-progress-universal",
      "card-layout-universal",
      "ribbon-header-universal",
      "boxed-sections-universal",
      "left-border-universal",
      "floating-header-universal",
      "monochrome-elegant-universal",
      // 2025 Second Batch Universal Profile Templates
      "gradient-header-universal",
      "split-pane-universal",
      "icon-bar-universal",
      "modern-minimalist-universal",
      "bold-typography-universal",
      "geometric-shapes-universal",
      "color-block-universal",
      "thin-border-universal",
      "asymmetric-layout-universal",
      "classic-serif-universal",
      "professional-compact-universal",
      "wide-margin-universal",
      "top-bar-universal",
      "corner-accent-universal",
      "striped-background-universal",
      "circular-elements-universal",
      "minimal-lines-universal",
      "bold-section-headers-universal",
      "two-tone-split-universal",
      "clean-modern-universal",
      // 2025 Third Batch Universal Profile Templates
      "watermark-style-universal",
      "magazine-layout-universal",
      "hexagonal-pattern-universal",
      "compact-elite-universal",
      "diamond-accent-universal",
      "zigzag-border-universal",
      "stacked-sections-universal",
      "dotted-grid-universal",
      "wave-pattern-universal",
      "chevron-accent-universal",
      "spotlight-header-universal",
      "layered-cards-universal",
      "angular-modern-universal",
      "rounded-corners-universal",
      "retro-professional-universal",
      "newspaper-style-universal",
      "triangular-elements-universal",
      "parallax-style-universal",
      "vertical-timeline-universal",
      "infinity-loop-universal",
      // 2025 New Universal Professional Templates (Batch 5)
      "executive-corner-accent",
      "minimal-elegance-universal",
      "professional-divider",
      "modern-corporate-grid",
      "business-sidebar-pro",
      "clean-two-column-universal",
      "professional-header-banner",
      "executive-timeline-modern",
      "corporate-border-frame",
      "minimalist-modern-pro",
      "professional-accent-bar",
      "business-clean-layout",
      "executive-split-design",
      "modern-professional-box",
      "corporate-minimalist-pro",
      "professional-vertical-line",
      "business-modern-grid",
      "executive-clean-split",
      "minimal-corporate-pro",
      "professional-modern-edge",
      // 2025 Simple Universal Professional Templates (Batch 6)
      "clean-professional-simple",
      "simple-executive-layout",
      "minimal-pro-layout",
      "professional-clean-simple",
      "corporate-simple-template",
      "modern-simple-pro",
      "executive-simple-clean",
      "business-simple-modern",
      "professional-easy-read",
      "clean-corporate-simple",
      "simple-modern-executive",
      "minimalist-pro-simple",
      "professional-straightforward",
      "executive-direct-layout",
      "business-clear-template",
      "simple-professional-clean",
      "corporate-easy-layout",
      "modern-clear-pro",
      "professional-plain-simple",
      "executive-plain-layout",
      "simple-business-clean",
      "minimal-direct-template",
      "professional-basic-modern",
      "clean-basic-executive",
      "simple-clear-business",
      "modern-plain-pro",
      "executive-easy-template",
      "professional-readable-layout",
      "clean-readable-pro",
      "simple-structured-template",
    ],
  },
  {
    id: "fresh-graduates",
    name: "Fresh Graduates & Students",
    description: "Entry-level templates for recent graduates and students",
    icon: GraduationCap,
    color: "#10b981",
    gradientFrom: "#10b981",
    gradientTo: "#059669",
    templateIds: [
      "graduate",
      "starter",
      "fresher",
      "premium-fresher",
      "fresher-elite",
      "fresher-minimal-grid",
      "fresher-dark-professional",
      "fresher-color-accent",
      "fresher-timeline",
      "fresher-skills-first",
      "fresher-card-based",
      "fresher-two-tone",
      "fresher-centered-elegant",
      "fresher-geometric",
      "fresher-achievement",
      "fresher-modern-two-column",
      "fresher-professional-sidebar",
      "fresher-clean-modern",
      "fresher-tech-split",
      "fresher-executive-style",
      "fresher-bold-header",
      "fresher-minimalist-two-column",
      "fresher-creative-edge",
      "fresher-professional-grid",
      "fresher-modern-classic",
      "fresher-split-layout",
      "fresher-compact-pro",
      "fresher-elegant-sidebar",
      "fresher-tech-modern",
      "fresher-professional-minimal",
      // New 2024 Fresher Templates
      "graduate-momentum",
      "entry-elite",
      "freshers-vision",
      "graduate-prime",
      "entry-horizon",
      "freshers-crafted",
      "graduate-zenith",
      "entry-sphere",
      // 2025 New Fresher Templates
      "fresher-neon-accent",
      "fresher-glassmorphism",
      "fresher-progressive",
      "fresher-polaroid-style",
      "fresher-ribbon-style",
      "fresher-double-column",
      "fresher-gradient-border",
      "fresher-circular-progress",
      "fresher-modern-tabs",
      "fresher-lightweight",
      "fresher-timeline-dots",
      "fresher-box-shadow",
      "fresher-step-by-step",
      "fresher-left-stripe",
      "fresher-top-bottom",
      "fresher-dash-border",
      "fresher-iconography",
      "fresher-modern-split",
      "fresher-wave-header",
      "fresher-academic-style",
    ],
  },
  {
    id: "software-technology",
    name: "Software & Technology",
    description: "Resume templates for developers, engineers, and tech professionals",
    icon: Code,
    color: "#3b82f6",
    gradientFrom: "#3b82f6",
    gradientTo: "#2563eb",
    templateIds: [
      "frontend",
      "backend",
      "fullstack",
      "senior",
      "senior-frontend",
      "senior-backend",
      "software",
      "tech-grid",
      // New Software Development Templates
      "java-developer",
      "dotnet-developer",
      "devops-engineer",
      "cloud-architect",
      "mobile-developer",
      "react-native-developer",
      "data-engineer",
      "machine-learning-engineer",
      "qa-automation-engineer",
      "security-engineer",
      "python-developer",
      "nodejs-developer",
      "react-developer",
      "go-developer",
      "kubernetes-engineer",
      // Senior/Lead Software Engineering Templates
      "senior-java-developer",
      "senior-dotnet-developer",
      "senior-devops-engineer",
      "lead-backend-engineer",
      "lead-frontend-engineer",
      "senior-fullstack-developer",
      "principal-software-engineer",
      "staff-engineer",
      "engineering-manager",
      "solutions-architect",
      "senior-mobile-engineer",
      "platform-engineer",
      "site-reliability-engineer",
      "backend-api-specialist",
      "frontend-architect",
      // New Software Engineering Templates
      "code-minimal",
      "tech-stack-pro",
      "github-style",
      "developer-grid",
      "terminal-theme",
      "algo-engineer",
      "fullstack-modern",
      "devops-pro",
      "ml-engineer",
      // New 2024 Tech Templates
      "code-craftsman",
      "tech-pioneer",
      "dev-architecture",
      "software-master",
      "tech-vanguard",
      "code-sphere",
      "dev-elite",
      "tech-horizon",
      "software-craftsman",
      "code-vision",
      "dev-prime",
      "tech-crafted",
      "software-vision",
      "code-pinnacle",
      "dev-momentum",
      // 2025 New Software/Tech Templates
      "dark-mode-dev",
      "code-snippet",
      "api-doc",
      "stackoverflow-inspired",
      "github-profile",
      "terminal-console",
      "json-resume",
      "monospace-tech",
      "blueprint-design",
      "system-architect",
      "cloud-native",
      "microservices-dev",
      "agile-scrum",
      "tech-lead",
      "open-source",
      "fullstack-pro",
      "data-science",
      "cyber-security",
      "blockchain-dev",
      "ai-engineer",
      "mobile-dev",
      // 2025 New Software/Tech Templates (Batch 3)
      "react-frontend-pro",
      "node-backend-specialist",
      "fullstack-engineer",
      "python-developer-pro",
      "java-enterprise-template",
      "devops-automation",
      "cloud-solutions-architect",
      "microservices-expert",
      "kubernetes-specialist",
      "docker-container-pro",
      "graphql-developer",
      "typescript-expert",
      "vuejs-developer",
      "angular-specialist",
      "springboot-developer",
      "django-framework-pro",
      "aws-cloud-engineer",
      "azure-devops-specialist",
      "gcp-architect",
      "serverless-developer",
      // 2025 New Software/Tech Templates (Batch 4)
      "rust-developer-pro",
      "scala-engineer",
      "elixir-developer",
      "swift-ios-developer",
      "kotlin-android-dev",
      "flutter-mobile-dev",
      "react-native-expert",
      "tensorflow-ml-engineer",
      "pytorch-developer",
      "mongodb-specialist",
      "postgresql-expert",
      "redis-cache-specialist",
      "elasticsearch-dev",
      "kafka-streaming-expert",
      "cicd-pipeline-engineer",
    ],
  },
  {
    id: "creative-design",
    name: "Creative & Design",
    description: "Modern creative templates for designers and creative professionals",
    icon: Palette,
    color: "#ec4899",
    gradientFrom: "#ec4899",
    gradientTo: "#db2777",
    templateIds: [
      "creative-accent",
      "modern",
      "elegant-serif",
      // New Creative Templates
      "artistic-bold",
      "designer-showcase",
      "creative-timeline",
      "colorful-modern",
      "asymmetric-creative",
      // New 2024 Creative Templates
      "creative-canvas",
      "design-maestro",
      "artistic-vision",
      "creative-pulse",
      "design-pinnacle",
      "artistic-horizon",
      "creative-crafted",
      "design-sphere",
      "artistic-momentum",
      "creative-horizon",
      // 2025 New Creative Templates
      "magazine-creative",
      "portfolio-showcase",
      "artistic-grid",
      "bold-typography",
      "color-splash",
      "minimal-chic",
      "photography-layout",
      "brand-identity",
      "vintage-poster",
      "modern-artist",
      "gallery-layout",
      "editorial-style",
      "urban-designer",
      "pastel-creative",
      "neon-artist",
      "geometric-creative",
      "typewriter-style",
      "ink-brush",
      "collage-art",
      "digital-canvas",
      // 2025 New Creative/Design Templates (Batch 2)
      "portfolio-minimalist",
      "creative-showcase-grid",
      "art-director-modern",
      "uiux-designer-pro",
      "graphic-design-pro",
      "brand-designer-template",
      "motion-graphics-artist",
      "illustration-portfolio",
      "photography-pro-template",
      "video-editor-creative",
      "threed-modeling-artist",
      "web-designer-modern",
      "product-designer-ux",
      "interaction-designer",
      "visual-storyteller-template",
    ],
  },
  {
    id: "business-leadership",
    name: "Business & Leadership",
    description: "Executive and leadership templates for senior professionals",
    icon: Briefcase,
    color: "#8b5cf6",
    gradientFrom: "#8b5cf6",
    gradientTo: "#7c3aed",
    templateIds: [
      "executive",
      "sapphire-executive",
      "luxury-timeline",
      "corporate-executive",
      "analyst",
      // 2025 New Business Leadership Templates
      "executive-leadership",
      "ceo-profile",
      "strategic-leader",
      "director-level",
      "vp-executive",
    ],
  },
  {
    id: "healthcare-medical",
    name: "Healthcare & Medical",
    description: "Professional templates for healthcare and medical professionals",
    icon: Heart,
    color: "#ef4444",
    gradientFrom: "#ef4444",
    gradientTo: "#dc2626",
    templateIds: [
      "medical-professional",
      "healthcare-two-column",
      "nurse-specialist",
      "medical-executive",
      "clinical-minimal",
      // 2025 New Healthcare Templates
      "medical-certification",
      "clinical-excellence",
      "healthcare-professional",
      "nursing-specialist",
      "medical-research",
    ],
  },
  {
    id: "education-teaching",
    name: "Education & Teaching",
    description: "Templates designed for educators and academic professionals",
    icon: BookOpen,
    color: "#06b6d4",
    gradientFrom: "#06b6d4",
    gradientTo: "#0891b2",
    templateIds: [
      "teacher-professional",
      "academic-scholar",
      "educator-modern",
      "teaching-certified",
      "student-educator",
      // 2025 New Education Templates
      "teaching-excellence",
      "modern-educator-profession",
      "academic-educator",
      "curriculum-developer",
      "student-engagement",
    ],
  },
  {
    id: "finance-accounting",
    name: "Finance & Accounting",
    description: "Professional templates for finance and accounting experts",
    icon: DollarSign,
    color: "#84cc16",
    gradientFrom: "#84cc16",
    gradientTo: "#65a30d",
    templateIds: [
      "cpa-professional",
      "finance-analyst",
      "accounting-executive",
      "auditor",
      "finance-two-column",
      // 2025 New Finance Templates
      "financial-analyst",
      "accounting-pro",
      "investment-banker",
      "tax-specialist",
      "audit-expert",
    ],
  },
  {
    id: "sales-marketing",
    name: "Sales & Marketing",
    description: "Dynamic templates for sales and marketing professionals",
    icon: TrendingUp,
    color: "#f97316",
    gradientFrom: "#f97316",
    gradientTo: "#ea580c",
    templateIds: [
      "sales-executive",
      "marketing-professional",
      "sales-marketing-hybrid",
      "digital-marketer",
      "sales-manager",
      // 2025 New Sales & Marketing Templates
      "sales-achievement",
      "marketing-strategist",
      "digital-marketing-pro",
      "brand-manager",
      "executive-sales-leader",
    ],
  },
  {
    id: "legal-consulting",
    name: "Legal & Consulting",
    description: "Refined templates for legal and consulting professionals",
    icon: Scale,
    color: "#6366f1",
    gradientFrom: "#6366f1",
    gradientTo: "#4f46e5",
    templateIds: [
      "attorney-professional",
      "legal-counsel",
      "consultant",
      "legal-executive",
      "paralegal",
      // 2025 New Legal Templates
      "corporate-legal-counsel",
      "corporate-law",
      "litigation-attorney",
      "compliance-officer",
      "legal-advisor",
    ],
  },
  {
    id: "operations-management",
    name: "Operations & Project Management",
    description: "Strategic templates for operations and project managers",
    icon: Settings,
    color: "#14b8a6",
    gradientFrom: "#14b8a6",
    gradientTo: "#0d9488",
    templateIds: [
      "project-manager-pmp",
      "operations-manager",
      "pm-executive",
      "agile-scrum",
      "operations-two-column",
      // 2025 New Operations Templates
      "project-manager-pro",
      "operations-excellence",
      "process-improvement",
      "supply-chain-manager",
      "agile-project-lead",
    ],
  },
];

// Helper function to get category by id
export const getCategoryById = (id: string): ProfessionCategory | undefined => {
  return professionCategories.find((cat) => cat.id === id);
};

// Helper function to get templates for a category
export const getTemplatesForCategory = (categoryId: string): string[] => {
  const category = getCategoryById(categoryId);
  return category?.templateIds || [];
};
