import {
  Code,
  Briefcase,
  Palette,
  GraduationCap,
  Star,
  Heart,
  BookOpen,
  DollarSign,
  TrendingUp,
  Scale,
  Settings,
  Sparkles,
  Wrench,
  Users,
  Utensils,
  Home,
} from "lucide-react";

export interface ProfessionCategory {
  id: string;
  name: string;
  description: string;
  icon: any;
  color: string;
  gradientFrom: string;
  gradientTo: string;
  templateIds: string[];
  isAll?: boolean; // Special flag for the "All" category
}

export const professionCategories: ProfessionCategory[] = [
  {
    id: "all",
    name: "All Templates",
    description: "Browse all our professionally designed resume templates across all categories",
    icon: Sparkles,
    color: "#6366f1",
    gradientFrom: "#6366f1",
    gradientTo: "#8b5cf6",
    isAll: true,
    templateIds: [
      "algo-engineer",
      "artistic-bold",
      "artistic-horizon",
      "artistic-momentum",
      "artistic-vision",
      "asymmetric-creative",
      "backend",
      "backend-api-specialist",
      "bold-headline",
      "border-frame-universal",
      "bordered-elegance",
      "business-elite",
      "business-modern",
      "clean-corporate",
      "cloud-architect",
      "code-craftsman",
      "code-minimal",
      "colorful-modern",
      "column-divide",
      "compact-professional",
      "contemporary-split",
      "corporate-blue",
      "corporate-clean",
      "creative-accent",
      "creative-canvas",
      "creative-crafted",
      "creative-horizon",
      "creative-pulse",
      "creative-timeline",
      "data-engineer",
      "design-maestro",
      "design-pinnacle",
      "design-sphere",
      "designer-showcase",
      "dev-architecture",
      "developer-grid",
      "devops-engineer",
      "devops-pro",
      "dotnet-developer",
      "elegant-professional",
      "elegant-serif",
      "engineering-manager",
      "executive-letterhead-universal",
      "executive-minimal",
      "fresher",
      "fresher-achievement",
      "fresher-bold-header",
      "fresher-card-based",
      "fresher-centered-elegant",
      "fresher-clean-modern",
      "fresher-color-accent",
      "fresher-compact-pro",
      "fresher-creative-edge",
      "fresher-dark-professional",
      "fresher-elegant-sidebar",
      "fresher-elite",
      "fresher-executive-style",
      "fresher-geometric",
      "fresher-minimal-grid",
      "fresher-minimalist-two-column",
      "fresher-modern-classic",
      "fresher-modern-two-column",
      "fresher-professional-grid",
      "fresher-professional-minimal",
      "fresher-professional-sidebar",
      "fresher-skills-first",
      "fresher-split-layout",
      "fresher-tech-modern",
      "fresher-tech-split",
      "fresher-timeline",
      "fresher-two-tone",
      "frontend",
      "frontend-architect",
      "fullstack",
      "fullstack-modern",
      "github-style",
      "go-developer",
      "gradient-header-universal",
      "graduate",
      "java-developer",
      "kubernetes-engineer",
      "lead-backend-engineer",
      "lead-frontend-engineer",
      "machine-learning-engineer",
      "magazine-creative",
      "minimal",
      "minimalist-pro",
      "ml-engineer",
      "mobile-developer",
      "modern",
      "modern-business",
      "modern-professional",
      "nodejs-developer",
      "platform-engineer",
      "portfolio-showcase",
      "premium-elite",
      "premium-fresher",
      "premium-pro",
      "premium-universal",
      "principal-software-engineer",
      "professional",
      "professional-classic",
      "professional-grid",
      "professional-timeline",
      "python-developer",
      "qa-automation-engineer",
      "react-developer",
      "react-native-developer",
      "refined",
      "security-engineer",
      "senior",
      "senior-backend",
      "senior-devops-engineer",
      "senior-dotnet-developer",
      "senior-frontend",
      "senior-fullstack-developer",
      "senior-java-developer",
      "senior-mobile-engineer",
      "sidebar-accent",
      "site-reliability-engineer",
      "software",
      "solutions-architect",
      "staff-engineer",
      "starter",
      "swiss-style-universal",
      "tech-grid",
      "tech-pioneer",
      "tech-stack-pro",
      "terminal-theme",
      "two-tone-classic"
    ],
  },
  {
    id: "universal-professional",
    name: "Universal Professional",
    description: "Versatile templates suitable for all industries and roles",
    icon: Star,
    color: "#f59e0b",
    gradientFrom: "#f59e0b",
    gradientTo: "#d97706",
    templateIds: [
      "professional",
      "minimal",
      "premium-universal",
      "premium-pro",
      "refined",
      "premium-elite",
      "bold-headline",
      "contemporary-split",
      "corporate-blue",
      "minimalist-pro",
      "business-modern",
      "professional-timeline",
      "clean-corporate",
      "modern-professional",
      "elegant-professional",
      "professional-grid",
      "business-elite",
      "corporate-clean",
      "professional-classic",
      "modern-business",
      "executive-minimal",
      "sidebar-accent",
      "two-tone-classic",
      "bordered-elegance",
      "column-divide",
      "compact-professional",
      "swiss-style-universal",
      "executive-letterhead-universal",
      "border-frame-universal",
      "gradient-header-universal"
    ],
  },
  {
    id: "fresh-graduates",
    name: "Fresh Graduates & Students",
    description: "Entry-level templates for recent graduates and students",
    icon: GraduationCap,
    color: "#10b981",
    gradientFrom: "#10b981",
    gradientTo: "#059669",
    templateIds: [
      "graduate",
      "starter",
      "fresher",
      "premium-fresher",
      "fresher-elite",
      "fresher-minimal-grid",
      "fresher-dark-professional",
      "fresher-color-accent",
      "fresher-timeline",
      "fresher-skills-first",
      "fresher-card-based",
      "fresher-two-tone",
      "fresher-centered-elegant",
      "fresher-geometric",
      "fresher-achievement",
      "fresher-modern-two-column",
      "fresher-professional-sidebar",
      "fresher-clean-modern",
      "fresher-tech-split",
      "fresher-executive-style",
      "fresher-bold-header",
      "fresher-minimalist-two-column",
      "fresher-creative-edge",
      "fresher-professional-grid",
      "fresher-modern-classic",
      "fresher-split-layout",
      "fresher-compact-pro",
      "fresher-elegant-sidebar",
      "fresher-tech-modern",
      "fresher-professional-minimal"
    ],
  },
  {
    id: "software-technology",
    name: "Software & Technology",
    description: "Resume templates for developers, engineers, and tech professionals",
    icon: Code,
    color: "#3b82f6",
    gradientFrom: "#3b82f6",
    gradientTo: "#2563eb",
    templateIds: [
      "frontend",
      "backend",
      "fullstack",
      "senior",
      "senior-frontend",
      "senior-backend",
      "software",
      "tech-grid",
      "java-developer",
      "dotnet-developer",
      "devops-engineer",
      "cloud-architect",
      "mobile-developer",
      "react-native-developer",
      "data-engineer",
      "machine-learning-engineer",
      "qa-automation-engineer",
      "security-engineer",
      "python-developer",
      "nodejs-developer",
      "react-developer",
      "go-developer",
      "kubernetes-engineer",
      "senior-java-developer",
      "senior-dotnet-developer",
      "senior-devops-engineer",
      "lead-backend-engineer",
      "lead-frontend-engineer",
      "senior-fullstack-developer",
      "principal-software-engineer",
      "staff-engineer",
      "engineering-manager",
      "solutions-architect",
      "senior-mobile-engineer",
      "platform-engineer",
      "site-reliability-engineer",
      "backend-api-specialist",
      "frontend-architect",
      "code-minimal",
      "tech-stack-pro",
      "github-style",
      "developer-grid",
      "terminal-theme",
      "algo-engineer",
      "fullstack-modern",
      "devops-pro",
      "ml-engineer",
      "code-craftsman",
      "tech-pioneer",
      "dev-architecture"
    ],
  },
  {
    id: "creative-design",
    name: "Creative & Design",
    description: "Modern creative templates for designers and creative professionals",
    icon: Palette,
    color: "#ec4899",
    gradientFrom: "#ec4899",
    gradientTo: "#db2777",
    templateIds: [
      "creative-accent",
      "modern",
      "elegant-serif",
      "artistic-bold",
      "designer-showcase",
      "creative-timeline",
      "colorful-modern",
      "asymmetric-creative",
      "creative-canvas",
      "design-maestro",
      "artistic-vision",
      "creative-pulse",
      "design-pinnacle",
      "artistic-horizon",
      "creative-crafted",
      "design-sphere",
      "artistic-momentum",
      "creative-horizon",
      "magazine-creative",
      "portfolio-showcase"
    ],
  },
  {
    id: "business-leadership",
    name: "Business & Leadership",
    description: "Executive and leadership templates for senior professionals",
    icon: Briefcase,
    color: "#8b5cf6",
    gradientFrom: "#8b5cf6",
    gradientTo: "#7c3aed",
    templateIds: [],
  },
  {
    id: "healthcare-medical",
    name: "Healthcare & Medical",
    description: "Professional templates for healthcare and medical professionals",
    icon: Heart,
    color: "#ef4444",
    gradientFrom: "#ef4444",
    gradientTo: "#dc2626",
    templateIds: [],
  },
  {
    id: "education-teaching",
    name: "Education & Teaching",
    description: "Templates designed for educators and academic professionals",
    icon: BookOpen,
    color: "#06b6d4",
    gradientFrom: "#06b6d4",
    gradientTo: "#0891b2",
    templateIds: [],
  },
  {
    id: "finance-accounting",
    name: "Finance & Accounting",
    description: "Professional templates for finance and accounting experts",
    icon: DollarSign,
    color: "#84cc16",
    gradientFrom: "#84cc16",
    gradientTo: "#65a30d",
    templateIds: [],
  },
  {
    id: "sales-marketing",
    name: "Sales & Marketing",
    description: "Dynamic templates for sales and marketing professionals",
    icon: TrendingUp,
    color: "#f97316",
    gradientFrom: "#f97316",
    gradientTo: "#ea580c",
    templateIds: [],
  },
  {
    id: "legal-consulting",
    name: "Legal & Consulting",
    description: "Refined templates for legal and consulting professionals",
    icon: Scale,
    color: "#6366f1",
    gradientFrom: "#6366f1",
    gradientTo: "#4f46e5",
    templateIds: [],
  },
  {
    id: "operations-management",
    name: "Operations & Project Management",
    description: "Strategic templates for operations and project managers",
    icon: Settings,
    color: "#14b8a6",
    gradientFrom: "#14b8a6",
    gradientTo: "#0d9488",
    templateIds: [],
  },
  {
    id: "engineering",
    name: "Engineering",
    description: "Professional templates for engineering and technical professionals",
    icon: Wrench,
    color: "#475569",
    gradientFrom: "#475569",
    gradientTo: "#334155",
    templateIds: [],
  },
  {
    id: "human-resources",
    name: "Human Resources",
    description: "HR and people operations templates for talent management professionals",
    icon: Users,
    color: "#be185d",
    gradientFrom: "#be185d",
    gradientTo: "#9f1239",
    templateIds: [],
  },
  {
    id: "hospitality-culinary",
    name: "Hospitality & Culinary",
    description: "Templates for hospitality, culinary, and event management professionals",
    icon: Utensils,
    color: "#92400e",
    gradientFrom: "#92400e",
    gradientTo: "#78350f",
    templateIds: [],
  },
  {
    id: "real-estate-construction",
    name: "Real Estate & Construction",
    description: "Templates for real estate, property management, and construction professionals",
    icon: Home,
    color: "#15803d",
    gradientFrom: "#15803d",
    gradientTo: "#166534",
    templateIds: [],
  },
];

// Helper function to get category by id
export const getCategoryById = (id: string): ProfessionCategory | undefined => {
  return professionCategories.find((cat) => cat.id === id);
};

// Helper function to get templates for a category
export const getTemplatesForCategory = (categoryId: string): string[] => {
  const category = getCategoryById(categoryId);
  return category?.templateIds || [];
};
