export interface TemplateMeta {
  name: string;
  description: string;
  category: string;
  categorySlug: string;
}

export const categoryLabelMap: Record<string, string> = {
  software: "Software Development",
  freshers: "Freshers & Entry Level",
  accountants: "Accounting & Finance",
  teaching: "Teaching & Education",
  all: "All Professions",
};

// Auto-generated template metadata
// Total: 120 templates
// Generated: 2025-12-06T17:00:27.525Z

export const templateMetaMap: Record<string, TemplateMeta> = {
  "algo-engineer": {
    name: "Algo Engineer",
    description: "Algorithm and problem-solving focused layout ideal for competitive programmers.",
    category: "Engineering",
    categorySlug: "software",
  },
  "artistic-bold": {
    name: "Artistic Bold",
    description: "Bold artistic design with creative typography and unique visual elements for creatives.",
    category: "Creative",
    categorySlug: "all",
  },
  "artistic-vision": {
    name: "Artistic Vision",
    description: "Vision-focused artistic template with creative expression emphasis.",
    category: "Creative & Design",
    categorySlug: "creative-design",
  },
  "asymmetric-creative": {
    name: "Asymmetric Creative",
    description: "Asymmetric layout with creative sections breaking traditional resume conventions.",
    category: "Creative",
    categorySlug: "all",
  },
  "backend": {
    name: "Backend",
    description: "Professional backend resume template",
    category: "Software & Technology",
    categorySlug: "software",
  },
  "bold-headline": {
    name: "Bold Headline",
    description: "Powerful dark header template with bold typography, strong visual hierarchy, and impactful design for all roles.",
    category: "Universal",
    categorySlug: "all",
  },
  "border-frame-universal": {
    name: "Border Frame",
    description: "Elegant border frame design creating a polished, contained look.",
    category: "Universal Professional",
    categorySlug: "universal-professional",
  },
  "bordered-elegance": {
    name: "Bordered Elegance",
    description: "Refined design with decorative borders and elegant details for distinguished professionals.",
    category: "Universal",
    categorySlug: "all",
  },
  "business-elite": {
    name: "Business Elite",
    description: "High-end professional design with premium styling and executive presence.",
    category: "Universal",
    categorySlug: "all",
  },
  "business-modern": {
    name: "Business Modern",
    description: "Contemporary business style with grid-based skill display and modern typography.",
    category: "Universal",
    categorySlug: "all",
  },
  "clean-corporate": {
    name: "Clean Corporate",
    description: "Clean lines and structure with corporate professional styling and organized sections.",
    category: "Universal",
    categorySlug: "all",
  },
  "cloud-architect": {
    name: "Cloud Solutions Architect",
    description: "Executive-level template for cloud architects highlighting multi-cloud expertise and infrastructure design.",
    category: "Engineering",
    categorySlug: "software",
  },
  "code-craftsman": {
    name: "Code Craftsman",
    description: "Dark-themed code-style template with developer-focused design and terminal aesthetics.",
    category: "Engineering",
    categorySlug: "software-technology",
  },
  "code-minimal": {
    name: "Code Minimal",
    description: "Minimal tech-focused design with monospace accents perfect for software developers.",
    category: "Engineering",
    categorySlug: "software",
  },
  "colorful-modern": {
    name: "Colorful Modern",
    description: "Vibrant colors and modern design elements for creative professionals who stand out.",
    category: "Creative",
    categorySlug: "all",
  },
  "column-divide": {
    name: "Column Divide",
    description: "Balanced 50/50 column layout with clear vertical separator and organized content sections.",
    category: "Universal",
    categorySlug: "all",
  },
  "compact-professional": {
    name: "Compact Professional",
    description: "Space-efficient professional design that maximizes content while maintaining readability.",
    category: "Universal",
    categorySlug: "all",
  },
  "contemporary-split": {
    name: "Contemporary Split",
    description: "Bold 50/50 split design with dark sidebar, high contrast layout, and modern aesthetic for all professionals.",
    category: "Universal",
    categorySlug: "all",
  },
  "corporate-blue": {
    name: "Corporate Blue",
    description: "Classic corporate style with blue accents and emphasis on achievements and metrics.",
    category: "Universal",
    categorySlug: "all",
  },
  "corporate-clean": {
    name: "Corporate Clean",
    description: "Clean corporate aesthetic with professional hierarchy and structured layout.",
    category: "Universal",
    categorySlug: "all",
  },
  "creative-accent": {
    name: "Creative Accent",
    description: "Modern sidebar template with gradient accent panel, skill bars, and creative two-column layout for all professionals.",
    category: "Creative",
    categorySlug: "all",
  },
  "creative-canvas": {
    name: "Creative Canvas",
    description: "Artistic canvas-style template for creative professionals and designers.",
    category: "Creative & Design",
    categorySlug: "creative-design",
  },
  "creative-crafted": {
    name: "Creative Crafted",
    description: "Handcrafted design template emphasizing creative attention to detail.",
    category: "Creative & Design",
    categorySlug: "creative-design",
  },
  "creative-horizon": {
    name: "Creative Horizon",
    description: "Horizon-focused creative template with modern artistic elements.",
    category: "Creative & Design",
    categorySlug: "creative-design",
  },
  "creative-timeline": {
    name: "Creative Timeline",
    description: "Visual timeline design with artistic elements and creative career progression display.",
    category: "Creative",
    categorySlug: "all",
  },
  "data-engineer": {
    name: "Data Engineer",
    description: "Data-driven template for engineers building ETL pipelines, data warehouses, and big data solutions.",
    category: "Engineering",
    categorySlug: "software",
  },
  "design-maestro": {
    name: "Design Maestro",
    description: "Maestro-level design template for expert designers and creative leaders.",
    category: "Creative & Design",
    categorySlug: "creative-design",
  },
  "design-pinnacle": {
    name: "Design Pinnacle",
    description: "Peak design template showcasing excellence in creative work.",
    category: "Creative & Design",
    categorySlug: "creative-design",
  },
  "design-sphere": {
    name: "Design Sphere",
    description: "Circular design elements perfect for modern designers.",
    category: "Creative & Design",
    categorySlug: "creative-design",
  },
  "designer-showcase": {
    name: "Designer Showcase",
    description: "Portfolio-style showcase layout perfect for designers displaying their creative work.",
    category: "Creative",
    categorySlug: "all",
  },
  "dev-architecture": {
    name: "Dev Architecture",
    description: "Architectural layout emphasizing system design and development skills.",
    category: "Engineering",
    categorySlug: "software-technology",
  },
  "developer-grid": {
    name: "Developer Grid",
    description: "Grid-based layout optimized for showcasing projects and technical skills effectively.",
    category: "Engineering",
    categorySlug: "software",
  },
  "devops-engineer": {
    name: "DevOps Specialist",
    description: "Tech-forward template for DevOps engineers emphasizing CI/CD, containerization, and cloud automation.",
    category: "Engineering",
    categorySlug: "software",
  },
  "devops-pro": {
    name: "DevOps Pro",
    description: "DevOps and SRE specialized template emphasizing automation and reliability engineering.",
    category: "Engineering",
    categorySlug: "software",
  },
  "dotnet-developer": {
    name: ".NET Professional",
    description: "Microsoft-inspired clean design for .NET developers with ASP.NET Core and Azure cloud experience.",
    category: "Engineering",
    categorySlug: "software",
  },
  "elegant-professional": {
    name: "Elegant Professional",
    description: "Sophisticated elegant design with refined typography and premium professional look.",
    category: "Universal",
    categorySlug: "all",
  },
  "elegant-serif": {
    name: "Elegant Serif",
    description: "Sophisticated serif typography template with ornamental dividers, centered layout, and classic elegance for all fields.",
    category: "Universal",
    categorySlug: "all",
  },
  "engineering-manager": {
    name: "Engineering Manager",
    description: "Engineering management template emphasizing people leadership, technical direction, team growth, and delivery excellence.",
    category: "Engineering",
    categorySlug: "software",
  },
  "executive-letterhead-universal": {
    name: "Executive Letterhead",
    description: "Letterhead-inspired professional template with executive presence.",
    category: "Universal Professional",
    categorySlug: "universal-professional",
  },
  "executive-minimal": {
    name: "Executive Minimal",
    description: "Minimalist executive template focusing on leadership achievements.",
    category: "Universal Professional",
    categorySlug: "universal-professional",
  },
  "fresher": {
    name: "Fresher",
    description: "Professional fresher resume template",
    category: "Fresh Graduates",
    categorySlug: "fresh-graduates",
  },
  "fresher-achievement": {
    name: "Achievement Focus",
    description: "Achievement-focused layout with highlighted sections and award icons, perfect for emphasizing accomplishments and metrics.",
    category: "Early Career",
    categorySlug: "freshers",
  },
  "fresher-bold-header": {
    name: "Bold Header",
    description: "Eye-catching bold header design with strong visual impact and clear section hierarchy for fresh talent.",
    category: "Early Career",
    categorySlug: "freshers",
  },
  "fresher-card-based": {
    name: "Card Design",
    description: "Modern card-based layout with shadow effects and gray background, creating depth and visual hierarchy for all sections.",
    category: "Early Career",
    categorySlug: "freshers",
  },
  "fresher-centered-elegant": {
    name: "Centered Elegance",
    description: "Sophisticated center-aligned layout with elegant typography, decorative line elements, and refined styling.",
    category: "Early Career",
    categorySlug: "freshers",
  },
  "fresher-clean-modern": {
    name: "Clean Modern",
    description: "Minimalist modern design with exceptional readability and clean spacing, perfect for entry-level professionals.",
    category: "Early Career",
    categorySlug: "freshers",
  },
  "fresher-color-accent": {
    name: "Color Accent Sidebar",
    description: "Eye-catching colored sidebar with profile photo, contact info, and skills, paired with clean white content area.",
    category: "Early Career",
    categorySlug: "freshers",
  },
  "fresher-compact-pro": {
    name: "Compact Professional",
    description: "Space-efficient professional design maximizing content density while maintaining readability for graduates.",
    category: "Early Career",
    categorySlug: "freshers",
  },
  "fresher-creative-edge": {
    name: "Creative Edge",
    description: "Creative design with unique visual elements while maintaining professional standards for innovative freshers.",
    category: "Early Career",
    categorySlug: "freshers",
  },
  "fresher-dark-professional": {
    name: "Dark Professional",
    description: "Modern template with dark gradient header, white skills badges, and side accent bars for a sophisticated fresh graduate look.",
    category: "Early Career",
    categorySlug: "freshers",
  },
  "fresher-elegant-sidebar": {
    name: "Elegant Sidebar",
    description: "Elegant sidebar template with refined typography and sophisticated layout for polished fresh graduates.",
    category: "Early Career",
    categorySlug: "freshers",
  },
  "fresher-elite": {
    name: "Elite Entry",
    description: "Modern premium design with colored header and timeline layout, perfect for fresh graduates.",
    category: "Early Career",
    categorySlug: "freshers",
  },
  "fresher-executive-style": {
    name: "Executive Style",
    description: "Sophisticated executive-inspired design for ambitious fresh graduates targeting leadership programs.",
    category: "Early Career",
    categorySlug: "freshers",
  },
  "fresher-geometric": {
    name: "Geometric Shapes",
    description: "Creative template with geometric accent shapes (hexagons, circles) as decorative elements throughout the design.",
    category: "Early Career",
    categorySlug: "freshers",
  },
  "fresher-minimal-grid": {
    name: "Minimal Grid",
    description: "Clean 3-column grid layout with side border accent, perfect for showcasing education, skills, and early experience systematically.",
    category: "Early Career",
    categorySlug: "freshers",
  },
  "fresher-minimalist-two-column": {
    name: "Minimalist Two-Column",
    description: "Ultra-clean two-column minimalist layout emphasizing content clarity and professional simplicity.",
    category: "Early Career",
    categorySlug: "freshers",
  },
  "fresher-modern-classic": {
    name: "Modern Classic",
    description: "Perfect blend of modern aesthetics and classic professionalism for versatile entry-level applications.",
    category: "Early Career",
    categorySlug: "freshers",
  },
  "fresher-modern-two-column": {
    name: "Modern Two-Column",
    description: "Contemporary two-column design with clean sections and modern typography, ideal for showcasing skills and education side-by-side.",
    category: "Early Career",
    categorySlug: "freshers",
  },
  "fresher-professional-grid": {
    name: "Professional Grid",
    description: "Grid-based professional layout providing organized structure for education, skills, and early experience.",
    category: "Early Career",
    categorySlug: "freshers",
  },
  "fresher-professional-minimal": {
    name: "Professional Minimal",
    description: "Clean professional minimalist approach with focus on content over decoration for entry-level roles.",
    category: "Early Career",
    categorySlug: "freshers",
  },
  "fresher-professional-sidebar": {
    name: "Professional Sidebar",
    description: "Professional layout with left sidebar for contact and skills, providing a clean, organized structure for fresh graduates.",
    category: "Early Career",
    categorySlug: "freshers",
  },
  "fresher-skills-first": {
    name: "Skills Showcase",
    description: "Skills-prominent layout with large skill cards at the top, ideal for freshers with strong technical capabilities.",
    category: "Early Career",
    categorySlug: "freshers",
  },
  "fresher-split-layout": {
    name: "Split Layout",
    description: "Distinctive split-screen design creating visual interest while maintaining ATS compatibility for freshers.",
    category: "Early Career",
    categorySlug: "freshers",
  },
  "fresher-tech-modern": {
    name: "Tech Modern",
    description: "Modern technical design with tech-forward styling perfect for engineering and IT fresh graduates.",
    category: "Early Career",
    categorySlug: "freshers",
  },
  "fresher-tech-split": {
    name: "Tech Split",
    description: "Technical split-layout design optimized for tech freshers with emphasis on skills and projects.",
    category: "Early Career",
    categorySlug: "freshers",
  },
  "fresher-timeline": {
    name: "Timeline Journey",
    description: "Vertical timeline design with connecting lines and timeline dots showing your educational and professional journey chronologically.",
    category: "Early Career",
    categorySlug: "freshers",
  },
  "fresher-two-tone": {
    name: "Two-Tone Split",
    description: "Bold 50/50 split design with colored left half featuring white text and clean white right content area.",
    category: "Early Career",
    categorySlug: "freshers",
  },
  "frontend": {
    name: "Frontend",
    description: "Professional frontend resume template",
    category: "Software & Technology",
    categorySlug: "software",
  },
  "frontend-architect": {
    name: "Frontend Architect",
    description: "Frontend architecture template showcasing component libraries, performance engineering, build tooling, and frontend strategy.",
    category: "Engineering",
    categorySlug: "software",
  },
  "fullstack": {
    name: "Fullstack",
    description: "Professional fullstack resume template",
    category: "Software & Technology",
    categorySlug: "software",
  },
  "go-developer": {
    name: "Go Developer",
    description: "Minimalist Go/Golang template for developers building high-performance systems and microservices.",
    category: "Engineering",
    categorySlug: "software",
  },
  "gradient-header-universal": {
    name: "Gradient Header",
    description: "Gradient header adding modern visual appeal to professional resume.",
    category: "Universal Professional",
    categorySlug: "universal-professional",
  },
  "graduate": {
    name: "Graduate",
    description: "Professional graduate resume template",
    category: "Fresh Graduates",
    categorySlug: "fresh-graduates",
  },
  "java-developer": {
    name: "Java Professional",
    description: "Enterprise Java template with Spring Boot focus, highlighting microservices and API development expertise.",
    category: "Engineering",
    categorySlug: "software",
  },
  "lead-backend-engineer": {
    name: "Lead Backend Engineer",
    description: "Technical leadership template for backend engineers emphasizing distributed systems, API design, and engineering team management.",
    category: "Engineering",
    categorySlug: "software",
  },
  "lead-frontend-engineer": {
    name: "Lead Frontend Engineer",
    description: "Frontend leadership template highlighting modern frameworks, design systems, performance optimization, and cross-functional collaboration.",
    category: "Engineering",
    categorySlug: "software",
  },
  "machine-learning-engineer": {
    name: "ML Engineer",
    description: "AI/ML focused template highlighting deep learning, model deployment, and MLOps expertise.",
    category: "Engineering",
    categorySlug: "software",
  },
  "magazine-creative": {
    name: "Magazine Creative",
    description: "Professional magazine creative resume template",
    category: "Creative & Design",
    categorySlug: "creative",
  },
  "minimal": {
    name: "Minimal",
    description: "Professional minimal resume template",
    category: "Universal Professional",
    categorySlug: "universal-professional",
  },
  "minimalist-pro": {
    name: "Minimalist Pro",
    description: "Ultra-clean minimal design with lots of white space and subtle professional accents.",
    category: "Universal",
    categorySlug: "all",
  },
  "ml-engineer": {
    name: "ML Engineer",
    description: "Machine Learning engineer focused template with data science and AI project highlights.",
    category: "Engineering",
    categorySlug: "software",
  },
  "mobile-developer": {
    name: "Mobile Developer",
    description: "Modern mobile-focused template for iOS/Android developers with native and cross-platform experience.",
    category: "Engineering",
    categorySlug: "software",
  },
  "modern": {
    name: "Modern",
    description: "Professional modern resume template",
    category: "Universal Professional",
    categorySlug: "universal-professional",
  },
  "modern-business": {
    name: "Modern Business",
    description: "Modern business styling with fresh contemporary design and professional polish.",
    category: "Universal",
    categorySlug: "all",
  },
  "modern-professional": {
    name: "Modern Professional",
    description: "Modern design with accent colors, card-style sections, and contemporary layout.",
    category: "Universal",
    categorySlug: "all",
  },
  "nodejs-developer": {
    name: "Node.js Developer",
    description: "Backend Node.js template emphasizing Express, NestJS, microservices, and event-driven architecture.",
    category: "Engineering",
    categorySlug: "software",
  },
  "platform-engineer": {
    name: "Platform Engineer",
    description: "Platform engineering template highlighting developer experience, infrastructure platforms, and internal tooling leadership.",
    category: "Engineering",
    categorySlug: "software",
  },
  "portfolio-showcase": {
    name: "Portfolio Showcase",
    description: "Professional portfolio showcase resume template",
    category: "Creative & Design",
    categorySlug: "creative",
  },
  "premium-elite": {
    name: "Premium Elite",
    description: "Stunning gradient header design with modern typography, timeline elements, and visual hierarchy for all professionals.",
    category: "Universal",
    categorySlug: "all",
  },
  "premium-fresher": {
    name: "Graduate Plus",
    description: "Modern premium template with gradient design, skill levels, and ATS-friendly layout for fresh graduates.",
    category: "Early Career",
    categorySlug: "freshers",
  },
  "premium-pro": {
    name: "Accent Panel",
    description: "Modern premium design with side accent panel and sophisticated typography for all professions.",
    category: "Universal",
    categorySlug: "all",
  },
  "premium-universal": {
    name: "Universal Pro",
    description: "Elegant and simple ATS-friendly template suitable for all industries and experience levels.",
    category: "Universal",
    categorySlug: "all",
  },
  "principal-software-engineer": {
    name: "Principal Software Engineer",
    description: "Staff-level template for principal engineers showcasing technical vision, architecture decisions, and organization-wide impact.",
    category: "Engineering",
    categorySlug: "software",
  },
  "professional": {
    name: "Professional",
    description: "Professional professional resume template",
    category: "Universal Professional",
    categorySlug: "universal-professional",
  },
  "professional-classic": {
    name: "Professional Classic",
    description: "Classic timeless design with traditional professional layout and ATS-friendly structure.",
    category: "Universal",
    categorySlug: "all",
  },
  "professional-grid": {
    name: "Professional Grid",
    description: "Grid-based layout with organized sections and modern structured design.",
    category: "Universal",
    categorySlug: "all",
  },
  "professional-timeline": {
    name: "Professional Timeline",
    description: "Timeline-based experience section with vertical line connecting positions.",
    category: "Universal",
    categorySlug: "all",
  },
  "python-developer": {
    name: "Python Developer",
    description: "Python-focused template for developers working with Django, Flask, FastAPI, and data processing.",
    category: "Engineering",
    categorySlug: "software",
  },
  "qa-automation-engineer": {
    name: "QA Automation Engineer",
    description: "Test automation template emphasizing frameworks, CI/CD integration, and quality assurance expertise.",
    category: "Engineering",
    categorySlug: "software",
  },
  "react-developer": {
    name: "React Developer",
    description: "Frontend React template highlighting component architecture, TypeScript, and modern state management.",
    category: "Engineering",
    categorySlug: "software",
  },
  "react-native-developer": {
    name: "React Native Developer",
    description: "Cross-platform mobile development template emphasizing React Native and JavaScript expertise.",
    category: "Engineering",
    categorySlug: "software",
  },
  "refined": {
    name: "Refined",
    description: "Professional refined resume template",
    category: "Universal Professional",
    categorySlug: "universal-professional",
  },
  "security-engineer": {
    name: "Security Engineer",
    description: "Cybersecurity template for engineers specializing in penetration testing, SIEM, and compliance.",
    category: "Engineering",
    categorySlug: "software",
  },
  "senior": {
    name: "Senior",
    description: "Professional senior resume template",
    category: "Universal Professional",
    categorySlug: "universal-professional",
  },
  "senior-backend": {
    name: "Architecture Pro",
    description: "Robust template highlighting scalable architecture, reliability, and leadership impact.",
    category: "Engineering",
    categorySlug: "software",
  },
  "senior-frontend": {
    name: "Vibrant Professional",
    description: "Vibrant two-column experience with data-driven highlights.",
    category: "Design & Engineering",
    categorySlug: "software",
  },
  "senior-java-developer": {
    name: "Senior Java Developer",
    description: "Executive-level Java template highlighting enterprise architecture, Spring ecosystem, and team leadership in large-scale systems.",
    category: "Engineering",
    categorySlug: "software",
  },
  "senior-mobile-engineer": {
    name: "Senior Mobile Engineer",
    description: "Mobile leadership template showcasing iOS/Android expertise, app architecture, performance optimization, and mobile platform strategy.",
    category: "Engineering",
    categorySlug: "software",
  },
  "sidebar-accent": {
    name: "Sidebar Accent",
    description: "Professional left sidebar layout with bold accent colors and organized information hierarchy.",
    category: "Universal",
    categorySlug: "all",
  },
  "site-reliability-engineer": {
    name: "Site Reliability Engineer",
    description: "SRE template emphasizing system reliability, incident management, monitoring, and production operations at scale.",
    category: "Engineering",
    categorySlug: "software",
  },
  "software": {
    name: "Software",
    description: "Professional software resume template",
    category: "Software & Technology",
    categorySlug: "software",
  },
  "solutions-architect": {
    name: "Solutions Architect",
    description: "Enterprise solutions template for architects designing complex systems, client-facing solutions, and technical consulting.",
    category: "Engineering",
    categorySlug: "software",
  },
  "staff-engineer": {
    name: "Staff Engineer",
    description: "IC leadership template highlighting technical strategy, cross-team influence, and high-impact projects for staff-level engineers.",
    category: "Engineering",
    categorySlug: "software",
  },
  "starter": {
    name: "Starter",
    description: "Professional starter resume template",
    category: "Fresh Graduates",
    categorySlug: "fresh-graduates",
  },
  "swiss-style-universal": {
    name: "Swiss Style",
    description: "Swiss design principles with grid-based layout and minimalist aesthetic.",
    category: "Universal Professional",
    categorySlug: "universal-professional",
  },
  "tech-grid": {
    name: "Tech Grid",
    description: "Technical template with gradient header, 3-column skill grid, and card-style layout for technology professionals.",
    category: "Engineering",
    categorySlug: "software",
  },
  "tech-pioneer": {
    name: "Tech Pioneer",
    description: "Modern tech template with innovative design for technology pioneers.",
    category: "Engineering",
    categorySlug: "software-technology",
  },
  "tech-stack-pro": {
    name: "Tech Stack Pro",
    description: "Showcase your technology stack prominently with organized skill categorization.",
    category: "Engineering",
    categorySlug: "software",
  },
  "terminal-theme": {
    name: "Terminal Theme",
    description: "Terminal/CLI inspired design with dark accents appealing to command-line enthusiasts.",
    category: "Engineering",
    categorySlug: "software",
  },
  "two-tone-classic": {
    name: "Two-Tone Classic",
    description: "Elegant two-tone color scheme with classic typography and sophisticated styling.",
    category: "Universal",
    categorySlug: "all",
  },
};
